/**
 * The credits (`scripts/kits/credits.ts`): the README's block and the module
 * the app renders. A CC BY source credited wrongly, or not at all, is a
 * licence breach in every copy of the page.
 */

import { describe, expect, it } from 'vitest';

import {
  MODIFIED,
  README_END,
  README_START,
  licenceOf,
  renderCreditsModule,
  renderReadmeCredits,
} from '@/scripts/kits/credits';
import { LICENCES, SOURCES } from '@/scripts/kits/sources';

describe('renderReadmeCredits()', () => {
  it('is a marked block with one table row per source, linked to it and its licence', () => {
    const block = renderReadmeCredits(['muldjord', 'swirly']);
    expect(block.startsWith(README_START)).toBe(true);
    expect(block.endsWith(README_END)).toBe(true);

    const rows = block.split('\n').filter((l) => l.startsWith('| ['));
    expect(rows).toEqual([
      `| [MuldjordKit](${SOURCES.muldjord.url}) — ${SOURCES.muldjord.author} | [CC BY 4.0](${LICENCES['CC-BY-4.0'].url}) | ${SOURCES.muldjord.usedFor} |`,
      `| [Swirly Drums](${SOURCES.swirly.url}) — ${SOURCES.swirly.author} | [CC0 1.0](${LICENCES['CC0-1.0'].url}) | ${SOURCES.swirly.usedFor} |`,
    ]);
  });

  it('says what was done to the samples, which CC BY asks to be said', () => {
    expect(renderReadmeCredits(['muldjord'])).toContain(MODIFIED);
  });

  it("prints a source's required notice once, and none for a source that has none", () => {
    const withNotice = renderReadmeCredits(['muldjord', 'swirly']);
    expect(withNotice.split('Drum samples provided by DrumGizmo.org.').length - 1).toBe(1);
    expect(renderReadmeCredits(['swirly'])).not.toContain('DrumGizmo');
  });
});

describe('renderCreditsModule()', () => {
  it('carries every source it is given, with its licence by name, as data', () => {
    const text = renderCreditsModule(['virtuosity', 'muldjord']);
    expect(text).toMatch(/^\/\* Generated by scripts\/kits\/build\.ts/);
    const json = /KIT_CREDITS: KitCredit\[\] = (\[[\s\S]*\]);/.exec(text)?.[1];
    expect(json).toBeDefined();
    const credits: unknown = JSON.parse(json ?? '[]');
    expect(credits).toEqual([
      expect.objectContaining({ id: 'virtuosity', licence: 'CC0 1.0' }),
      expect.objectContaining({
        id: 'muldjord',
        licence: 'CC BY 4.0',
        notice: 'Drum samples provided by DrumGizmo.org.',
      }),
    ]);
  });
});

describe('licenceOf()', () => {
  it('links a standard licence to its own page', () => {
    expect(licenceOf('muldjord')).toEqual(LICENCES['CC-BY-4.0']);
  });

  it("links a grant that is no standard licence to that source's own grant, not another's", () => {
    // `permission` has no licence page; SM Drums' credit is its makers' post
    expect(licenceOf('smdrums')).toEqual({
      name: LICENCES.permission.name,
      url: SOURCES.smdrums.grant.at,
    });
    expect(renderReadmeCredits(['smdrums'])).toContain(`(${SOURCES.smdrums.grant.at})`);
  });
});
