/* Generated by scripts/kits/build.ts from scripts/kits/sources.ts. Do not edit. */

export interface KitCredit {
  id: string;
  title: string;
  author: string;
  url: string;
  licence: string;
  licenceUrl: string;
  usedFor: string;
  notice?: string;
}

/** What every shipped sample has had done to it. */
export const KIT_SAMPLES_MODIFIED = "trimmed, mixed to mono, level-matched and re-encoded as AAC";

/** Every library a shipped sample comes from. */
export const KIT_CREDITS: KitCredit[] = [
  {
    "id": "virtuosity",
    "title": "Virtuosity Drums",
    "author": "Versilian Studios & Karoryfer Samples",
    "url": "https://github.com/sfzinstruments/virtuosity_drums",
    "licence": "CC0 1.0",
    "licenceUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "usedFor": "Jazz kit, recorded percussion"
  },
  {
    "id": "vcsl",
    "title": "Versilian Community Sample Library",
    "author": "Versilian Studios",
    "url": "https://github.com/sgossner/VCSL",
    "licence": "CC0 1.0",
    "licenceUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "usedFor": "Woodblock, handclaps, tambourine"
  },
  {
    "id": "swirly",
    "title": "Swirly Drums",
    "author": "Karoryfer Samples",
    "url": "https://github.com/sfzinstruments/karoryfer.swirly-drums",
    "licence": "CC0 1.0",
    "licenceUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "usedFor": "Brush kit"
  },
  {
    "id": "muldjord",
    "title": "MuldjordKit",
    "author": "Lars Muldjord, FreePats stereo version",
    "url": "https://github.com/freepats/muldjordkit",
    "licence": "CC BY 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
    "usedFor": "Muldjord kit",
    "notice": "Drum samples provided by DrumGizmo.org."
  },
  {
    "id": "boochi44",
    "title": "Soulful Vintage, Hard Trap",
    "author": "Boochi44, from Michael Fischer's TR-808 set",
    "url": "https://github.com/Boochi44/free-drum-samples",
    "licence": "CC0 1.0",
    "licenceUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "usedFor": "Dusty sampler, Trap kit"
  }
];
