/* Generated by scripts/kits/build.ts from scripts/kits/sources.ts. Do not edit. */

export interface KitCredit {
  id: string;
  title: string;
  author: string;
  url: string;
  licence: string;
  licenceUrl: string;
  usedFor: string;
  notice?: string;
}

/** What every shipped sample has had done to it. */
export const KIT_SAMPLES_MODIFIED = "trimmed, mixed to mono, level-matched and re-encoded as AAC";

/** Every library a shipped sample comes from. */
export const KIT_CREDITS: KitCredit[] = [
  {
    "id": "virtuosity",
    "title": "Virtuosity Drums",
    "author": "Versilian Studios & Karoryfer Samples",
    "url": "https://github.com/sfzinstruments/virtuosity_drums",
    "licence": "CC0 1.0",
    "licenceUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "usedFor": "Jazz kit, recorded percussion"
  },
  {
    "id": "vcsl",
    "title": "Versilian Community Sample Library",
    "author": "Versilian Studios",
    "url": "https://github.com/sgossner/VCSL",
    "licence": "CC0 1.0",
    "licenceUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "usedFor": "Woodblock, handclaps, tambourine"
  },
  {
    "id": "swirly",
    "title": "Swirly Drums",
    "author": "Karoryfer Samples",
    "url": "https://github.com/sfzinstruments/karoryfer.swirly-drums",
    "licence": "CC0 1.0",
    "licenceUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "usedFor": "Brush kit"
  },
  {
    "id": "muldjord",
    "title": "MuldjordKit",
    "author": "Lars Muldjord, FreePats stereo version",
    "url": "https://github.com/freepats/muldjordkit",
    "licence": "CC BY 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
    "usedFor": "Muldjord kit",
    "notice": "Drum samples provided by DrumGizmo.org."
  },
  {
    "id": "boochi44",
    "title": "Soulful Vintage, Hard Trap",
    "author": "Boochi44, from Michael Fischer's TR-808 set",
    "url": "https://github.com/Boochi44/free-drum-samples",
    "licence": "CC0 1.0",
    "licenceUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "usedFor": "Dusty sampler, Trap kit"
  },
  {
    "id": "bigrusty",
    "title": "Big Rusty Drums",
    "author": "Karoryfer Samples",
    "url": "https://github.com/sfzinstruments/karoryfer.big-rusty-drums",
    "licence": "CC0 1.0",
    "licenceUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "usedFor": "Big Rusty kit; the Gogodze kit’s cymbals"
  },
  {
    "id": "unruly",
    "title": "Unruly Drums",
    "author": "Karoryfer Samples",
    "url": "https://github.com/sfzinstruments/karoryfer.unruly-drums",
    "licence": "CC0 1.0",
    "licenceUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "usedFor": "Unruly kit"
  },
  {
    "id": "gogodze",
    "title": "Gogodze Phu Vol II",
    "author": "Karoryfer Lecolds",
    "url": "https://github.com/sfzinstruments/karoryfer.gogodze-phu-vol-ii",
    "licence": "CC0 1.0",
    "licenceUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "usedFor": "Gogodze kit"
  },
  {
    "id": "drskit",
    "title": "DRSKit",
    "author": "Lars and Deva Muldjord, DrumGizmo, on a kit lent by DRSDrums",
    "url": "https://drumgizmo.org/wiki/doku.php?id=kits:drskit",
    "licence": "CC BY 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
    "usedFor": "DRS kit, DRS brushes",
    "notice": "Drum samples provided by DrumGizmo.org."
  },
  {
    "id": "salamander",
    "title": "Salamander Drumkit",
    "author": "Alexander Holm",
    "url": "https://rytmenpinne.wordpress.com/sounds-and-such/salamander-drumkit/",
    "licence": "Public domain",
    "licenceUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "usedFor": "Splash, china and second crash for the kits without them"
  },
  {
    "id": "frankensnare",
    "title": "Frankensnare",
    "author": "Karoryfer Samples",
    "url": "https://github.com/sfzinstruments/karoryfer.frankensnare",
    "licence": "CC0 1.0",
    "licenceUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "usedFor": "Snares for building your own kit; the tambourine"
  },
  {
    "id": "smdrums",
    "title": "SM Drums",
    "author": "Scott McLean, Tod Stillwell and Suleiman Ali",
    "url": "https://smmdrums.wordpress.com/",
    "licence": "Free use, by grant",
    "licenceUrl": "https://www.kvraudio.com/forum/viewtopic.php?t=433571",
    "usedFor": "SM Drums kit"
  },
  {
    "id": "osdk",
    "title": "The Open Source Drumkit",
    "author": "Real Music Media",
    "url": "https://github.com/crabacus/the-open-source-drumkit",
    "licence": "Public domain",
    "licenceUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "usedFor": "Open Source kit"
  },
  {
    "id": "worldperc",
    "title": "World Percussion",
    "author": "FreePats (Xavimart, Gonzalo and Roberto)",
    "url": "https://freepats.zenvoid.org/Percussion/world-and-rare-percussion.html",
    "licence": "CC0 1.0",
    "licenceUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "usedFor": "Shaker, cascara"
  },
  {
    "id": "bodyperc",
    "title": "Body Percussion",
    "author": "Karoryfer Samples (D. Smolken)",
    "url": "https://github.com/sfzinstruments/body_percussion",
    "licence": "CC0 1.0",
    "licenceUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "usedFor": "Handclap"
  }
];
