/**
 * The credits, from `sources.ts`: a block in the README and a data module the
 * app can render. Pure — `build.ts` writes what these return.
 */

import { LICENCES, SOURCES, type SourceId } from '@/scripts/kits/sources';

export const README_START = '<!-- kit-credits:start -->';
export const README_END = '<!-- kit-credits:end -->';

/** What every shipped sample has had done to it, which CC BY asks to be said. */
export const MODIFIED = 'trimmed, mixed to mono, level-matched and re-encoded as AAC';

/** The README's credits table and notices, between its markers. */
export function renderReadmeCredits(ids: SourceId[]): string {
  const rows = ids.map((id) => {
    const s = SOURCES[id];
    const lic = LICENCES[s.licence];
    return `| [${s.title}](${s.url}) — ${s.author} | [${lic.name}](${lic.url}) | ${s.usedFor} |`;
  });
  const notices = [
    ...new Set(ids.map((id) => SOURCES[id]).flatMap((s) => ('notice' in s ? [s.notice] : []))),
  ];
  return [
    README_START,
    '',
    '| Source | Licence | Used for |',
    '| --- | --- | --- |',
    ...rows,
    '',
    ...notices.map((n) => `**${n}**`),
    ...(notices.length ? [''] : []),
    `Every sample has been ${MODIFIED}, by \`scripts/kits/build.ts\`. Changed files from a CC BY source are under the same licence. Each source's licence, as it publishes it, is in [\`public/kits/LICENSES/\`](./public/kits/LICENSES/).`,
    '',
    README_END,
  ].join('\n');
}

/** `lib/app/breaks/kit-credits.generated.ts`. */
export function renderCreditsModule(ids: SourceId[]): string {
  const entries = ids.map((id) => {
    const s = SOURCES[id];
    const lic = LICENCES[s.licence];
    return {
      id,
      title: s.title,
      author: s.author,
      url: s.url,
      licence: lic.name,
      licenceUrl: lic.url,
      usedFor: s.usedFor,
      ...('notice' in s ? { notice: s.notice } : {}),
    };
  });
  return [
    '/* Generated by scripts/kits/build.ts from scripts/kits/sources.ts. Do not edit. */',
    '',
    'export interface KitCredit {',
    '  id: string;',
    '  title: string;',
    '  author: string;',
    '  url: string;',
    '  licence: string;',
    '  licenceUrl: string;',
    '  usedFor: string;',
    '  notice?: string;',
    '}',
    '',
    `/** What every shipped sample has had done to it. */`,
    `export const KIT_SAMPLES_MODIFIED = ${JSON.stringify(MODIFIED)};`,
    '',
    '/** Every library a shipped sample comes from. */',
    `export const KIT_CREDITS: KitCredit[] = ${JSON.stringify(entries, null, 2)};`,
    '',
  ].join('\n');
}
