/**
 * Who sits at the 3D drummer's kit (experiment): a cast of players, one
 * picked at random each time the drummer view opens.
 *
 * A persona is only how the figure looks — skin, build, hair, beard, clothes
 * and what they wear with them. It never moves a joint: the shoulders, hips
 * and limb lengths are the kit layout's (`BODY`), so every player reaches the
 * same drums with the same strokes and a bigger or slimmer build is girth on
 * the same skeleton.
 */

export type Figure = 'male' | 'female';

export type Build = 'slim' | 'average' | 'heavy' | 'muscular';

export type HairStyle =
  | 'bald'
  | 'crop'
  | 'mohawk'
  | 'spikes'
  | 'afro'
  | 'long'
  | 'bun'
  | 'pigtails'
  | 'dreads'
  | 'quiff'
  | 'ponytail'
  | 'bob'
  | 'mullet';

export type Beard = 'none' | 'stubble' | 'full' | 'goatee' | 'handlebar' | 'viking';

/** Something on the head, over the hair. */
export type Hat = 'beanie' | 'cap' | 'cowboy' | 'tophat' | 'bandana';

/** What's on top: a T-shirt, a vest that leaves the arms bare, or nothing at all. */
export type Top = 'tee' | 'vest' | 'bare';

export interface Persona {
  id: string;
  name: string;
  figure: Figure;
  build: Build;
  /** Colours, as CSS hex. */
  skin: string;
  hair: string;
  hairStyle: HairStyle;
  beard: Beard;
  top: Top;
  shirt: string;
  trousers: string;
  shoes: string;
  /** Headband, mohawk tips and the like: the loud colour. */
  accent: string;
  shades?: boolean;
  headband?: boolean;
  earrings?: boolean;
  chain?: boolean;
  lipstick?: boolean;
  hat?: Hat;
}

/** Skin, lightest to deepest. */
const SKIN = {
  porcelain: '#f2d6c4',
  fair: '#e6b896',
  olive: '#c99a70',
  tan: '#b07a55',
  brown: '#8c5a3c',
  deep: '#6a3f29',
  ebony: '#4a2b1d',
} as const;

export const PERSONAS: readonly Persona[] = [
  {
    // the drummer who played before there was a cast, exactly as he was
    id: 'original',
    name: 'The Original',
    figure: 'male',
    build: 'average',
    skin: '#c58c6a',
    hair: '#2a1c14',
    hairStyle: 'crop',
    beard: 'none',
    top: 'tee',
    shirt: '#2c4f6b',
    trousers: '#2a2f3a',
    shoes: '#202124',
    accent: '#2c4f6b',
  },
  {
    id: 'roxy',
    name: 'Roxy Riot',
    figure: 'female',
    build: 'slim',
    skin: SKIN.porcelain,
    hair: '#ff2f8e',
    hairStyle: 'mohawk',
    beard: 'none',
    top: 'vest',
    shirt: '#111111',
    trousers: '#1a1a1a',
    shoes: '#0d0d0d',
    accent: '#ff2f8e',
    earrings: true,
    lipstick: true,
    chain: true,
  },
  {
    id: 'thor',
    name: 'Big Thor',
    figure: 'male',
    build: 'heavy',
    skin: SKIN.fair,
    hair: '#c4692b',
    hairStyle: 'long',
    beard: 'viking',
    top: 'tee',
    shirt: '#3b3b3b',
    trousers: '#23262c',
    shoes: '#3a2414',
    accent: '#c4692b',
  },
  {
    id: 'marcus',
    name: 'Marcus "Thunder"',
    figure: 'male',
    build: 'muscular',
    skin: SKIN.ebony,
    hair: '#0e0b09',
    hairStyle: 'bald',
    beard: 'goatee',
    top: 'bare',
    shirt: SKIN.ebony,
    trousers: '#7a1f1a',
    shoes: '#f2f2f2',
    accent: '#f2c230',
    shades: true,
    chain: true,
  },
  {
    id: 'nia',
    name: 'Nia Groove',
    figure: 'female',
    build: 'average',
    skin: SKIN.deep,
    hair: '#1a110b',
    hairStyle: 'afro',
    beard: 'none',
    top: 'vest',
    shirt: '#f2a71b',
    trousers: '#22305a',
    shoes: '#f4f1ea',
    accent: '#e8432f',
    headband: true,
    earrings: true,
    lipstick: true,
  },
  {
    id: 'spike',
    name: 'Spike',
    figure: 'male',
    build: 'slim',
    skin: SKIN.fair,
    hair: '#36e0ff',
    hairStyle: 'spikes',
    beard: 'stubble',
    top: 'vest',
    shirt: '#e8432f',
    trousers: '#111111',
    shoes: '#111111',
    accent: '#36e0ff',
    earrings: true,
  },
  {
    id: 'raj',
    name: 'Raj the Metronome',
    figure: 'male',
    build: 'average',
    skin: SKIN.tan,
    hair: '#141010',
    hairStyle: 'bun',
    beard: 'full',
    top: 'tee',
    shirt: '#5c7a3a',
    trousers: '#2b2a28',
    shoes: '#5a3a22',
    accent: '#5c7a3a',
  },
  {
    id: 'lola',
    name: 'Lola Lightning',
    figure: 'female',
    build: 'muscular',
    skin: SKIN.brown,
    hair: '#f4d03f',
    hairStyle: 'pigtails',
    beard: 'none',
    top: 'vest',
    shirt: '#9b2fff',
    trousers: '#1b1b1b',
    shoes: '#9b2fff',
    accent: '#f4d03f',
    shades: true,
    lipstick: true,
  },
  {
    id: 'bubba',
    name: 'Bubba',
    figure: 'male',
    build: 'heavy',
    skin: SKIN.brown,
    hair: '#1c140f',
    hairStyle: 'crop',
    beard: 'handlebar',
    top: 'tee',
    shirt: '#b8352a',
    trousers: '#3a4a6a',
    shoes: '#3a2414',
    accent: '#f4f1ea',
    headband: true,
  },
  {
    id: 'jah',
    name: 'Jah Rhythm',
    figure: 'male',
    build: 'slim',
    skin: SKIN.deep,
    hair: '#24170f',
    hairStyle: 'dreads',
    beard: 'stubble',
    top: 'tee',
    shirt: '#2f8f46',
    trousers: '#e1c16e',
    shoes: '#24170f',
    accent: '#e8432f',
    shades: true,
  },
  {
    id: 'vex',
    name: 'Vex',
    figure: 'female',
    build: 'slim',
    skin: SKIN.olive,
    hair: '#0b0b0b',
    hairStyle: 'long',
    beard: 'none',
    top: 'vest',
    shirt: '#0b0b0b',
    trousers: '#0b0b0b',
    shoes: '#7a1f1a',
    accent: '#c40000',
    earrings: true,
    chain: true,
    lipstick: true,
  },
  {
    id: 'grizz',
    name: 'Grizz',
    figure: 'male',
    build: 'muscular',
    skin: SKIN.porcelain,
    hair: '#8c8c8c',
    hairStyle: 'bald',
    beard: 'full',
    top: 'vest',
    shirt: '#1e1e1e',
    trousers: '#2a2f3a',
    shoes: '#111111',
    accent: '#d9dde2',
    shades: true,
    earrings: true,
  },
  {
    id: 'mama',
    name: 'Mama Beats',
    figure: 'female',
    build: 'heavy',
    skin: SKIN.tan,
    hair: '#6b2a8f',
    hairStyle: 'bun',
    beard: 'none',
    top: 'tee',
    shirt: '#e86a9a',
    trousers: '#2a2f3a',
    shoes: '#f4f1ea',
    accent: '#f2c230',
    earrings: true,
    lipstick: true,
  },
  {
    id: 'ziggy',
    name: 'Ziggy Flash',
    figure: 'male',
    build: 'slim',
    skin: SKIN.porcelain,
    hair: '#ff7a00',
    hairStyle: 'afro',
    beard: 'none',
    top: 'bare',
    shirt: SKIN.porcelain,
    trousers: '#d9dde2',
    shoes: '#d9dde2',
    accent: '#36e0ff',
    shades: true,
    lipstick: true,
  },
  {
    id: 'tex',
    name: 'Tex',
    figure: 'male',
    build: 'heavy',
    skin: SKIN.tan,
    hair: '#5a3a22',
    hairStyle: 'crop',
    beard: 'handlebar',
    top: 'tee',
    shirt: '#8b3a2b',
    trousers: '#34507a',
    shoes: '#6b4226',
    accent: '#8a5a2b',
    hat: 'cowboy',
  },
  {
    id: 'duchess',
    name: 'The Duchess',
    figure: 'female',
    build: 'slim',
    skin: SKIN.ebony,
    hair: '#0b0b0b',
    hairStyle: 'bob',
    beard: 'none',
    top: 'vest',
    shirt: '#5b1f7a',
    trousers: '#111111',
    shoes: '#c40000',
    accent: '#c9a24a',
    hat: 'tophat',
    earrings: true,
    chain: true,
    lipstick: true,
  },
  {
    id: 'kenji',
    name: 'Kenji Kicks',
    figure: 'male',
    build: 'slim',
    skin: SKIN.fair,
    hair: '#0e0e10',
    hairStyle: 'quiff',
    beard: 'none',
    top: 'tee',
    shirt: '#f4f1ea',
    trousers: '#111111',
    shoes: '#c40000',
    accent: '#c40000',
  },
  {
    id: 'brandy',
    name: 'Brandy Blast',
    figure: 'female',
    build: 'heavy',
    skin: SKIN.fair,
    hair: '#b8321e',
    hairStyle: 'long',
    beard: 'none',
    top: 'vest',
    shirt: '#1d1d1d',
    trousers: '#2a2f3a',
    shoes: '#1d1d1d',
    accent: '#f2c230',
    hat: 'bandana',
    earrings: true,
    lipstick: true,
  },
  {
    id: 'mo',
    name: 'Mo Power',
    figure: 'male',
    build: 'muscular',
    skin: SKIN.brown,
    hair: '#1a120c',
    hairStyle: 'crop',
    beard: 'full',
    top: 'vest',
    shirt: '#3a3a3a',
    trousers: '#2a2f3a',
    shoes: '#111111',
    accent: '#e8432f',
    hat: 'beanie',
  },
  {
    id: 'ivy',
    name: 'Ivy',
    figure: 'female',
    build: 'average',
    skin: SKIN.olive,
    hair: '#2fbf71',
    hairStyle: 'ponytail',
    beard: 'none',
    top: 'tee',
    shirt: '#1f7a8c',
    trousers: '#1b1b1b',
    shoes: '#f4f1ea',
    accent: '#2fbf71',
    earrings: true,
  },
  {
    id: 'rex',
    name: 'Rex Mullet',
    figure: 'male',
    build: 'average',
    skin: SKIN.fair,
    hair: '#e6c35c',
    hairStyle: 'mullet',
    beard: 'stubble',
    top: 'vest',
    shirt: '#4a6fa5',
    trousers: '#34507a',
    shoes: '#f4f1ea',
    accent: '#4a6fa5',
    shades: true,
  },
  {
    id: 'kwame',
    name: 'Kwame',
    figure: 'male',
    build: 'heavy',
    skin: SKIN.ebony,
    hair: '#0e0b09',
    hairStyle: 'crop',
    beard: 'goatee',
    top: 'tee',
    shirt: '#f2c230',
    trousers: '#22305a',
    shoes: '#f4f1ea',
    accent: '#c40000',
    hat: 'cap',
    chain: true,
  },
  {
    id: 'sunny',
    name: 'Sunny Smash',
    figure: 'female',
    build: 'muscular',
    skin: SKIN.tan,
    hair: '#2a1c14',
    hairStyle: 'bun',
    beard: 'none',
    top: 'vest',
    shirt: '#ff7a00',
    trousers: '#111111',
    shoes: '#ff7a00',
    accent: '#36e0ff',
    hat: 'bandana',
    shades: true,
  },
  {
    id: 'priya',
    name: 'Priya',
    figure: 'female',
    build: 'slim',
    skin: SKIN.brown,
    hair: '#100c0a',
    hairStyle: 'long',
    beard: 'none',
    top: 'tee',
    shirt: '#c40000',
    trousers: '#1b1b1b',
    shoes: '#c9a24a',
    accent: '#c9a24a',
    earrings: true,
    lipstick: true,
  },
  {
    id: 'olaf',
    name: 'Olaf',
    figure: 'male',
    build: 'slim',
    skin: SKIN.porcelain,
    hair: '#ece8df',
    hairStyle: 'bald',
    beard: 'viking',
    top: 'tee',
    shirt: '#22305a',
    trousers: '#3a3a3a',
    shoes: '#3a2414',
    accent: '#c40000',
    hat: 'beanie',
  },
  {
    id: 'dex',
    name: 'Dex',
    figure: 'male',
    build: 'average',
    skin: SKIN.deep,
    hair: '#39d353',
    hairStyle: 'mohawk',
    beard: 'none',
    top: 'vest',
    shirt: '#111111',
    trousers: '#7a1f1a',
    shoes: '#111111',
    accent: '#39d353',
    earrings: true,
    chain: true,
  },
  {
    id: 'gran',
    name: 'Granny Groove',
    figure: 'female',
    build: 'heavy',
    skin: SKIN.fair,
    hair: '#d9d9de',
    hairStyle: 'bob',
    beard: 'none',
    top: 'tee',
    shirt: '#b39ddb',
    trousers: '#3a3a4a',
    shoes: '#f4f1ea',
    accent: '#e86a9a',
    shades: true,
    earrings: true,
    lipstick: true,
  },
  {
    id: 'paco',
    name: 'Paco Paradiddle',
    figure: 'male',
    build: 'average',
    skin: SKIN.tan,
    hair: '#141010',
    hairStyle: 'quiff',
    beard: 'handlebar',
    top: 'tee',
    shirt: '#d81b60',
    trousers: '#111111',
    shoes: '#f4f1ea',
    accent: '#d81b60',
    chain: true,
  },
  {
    id: 'zara',
    name: 'Zara Gold',
    figure: 'female',
    build: 'average',
    skin: SKIN.deep,
    hair: '#e0b24a',
    hairStyle: 'spikes',
    beard: 'none',
    top: 'vest',
    shirt: '#c0c4cc',
    trousers: '#111111',
    shoes: '#e0b24a',
    accent: '#e0b24a',
    earrings: true,
    lipstick: true,
  },
  {
    id: 'baron',
    name: 'The Baron',
    figure: 'male',
    build: 'heavy',
    skin: SKIN.porcelain,
    hair: '#8c8c8c',
    hairStyle: 'crop',
    beard: 'full',
    top: 'tee',
    shirt: '#6a1b2a',
    trousers: '#1b1b1b',
    shoes: '#111111',
    accent: '#6a1b2a',
    hat: 'tophat',
  },
  {
    id: 'skye',
    name: 'Skye',
    figure: 'female',
    build: 'slim',
    skin: SKIN.fair,
    hair: '#f4ecd8',
    hairStyle: 'ponytail',
    beard: 'none',
    top: 'vest',
    shirt: '#36a3ff',
    trousers: '#f4f1ea',
    shoes: '#36a3ff',
    accent: '#ff2f8e',
    hat: 'cap',
    lipstick: true,
  },
  {
    id: 'ali',
    name: 'Ali Anvil',
    figure: 'male',
    build: 'muscular',
    skin: SKIN.olive,
    hair: '#1a120c',
    hairStyle: 'crop',
    beard: 'stubble',
    top: 'bare',
    shirt: SKIN.olive,
    trousers: '#3a3a3a',
    shoes: '#111111',
    accent: '#e0b24a',
    chain: true,
  },
];

let lastPicked: string | undefined;

/**
 * A player for a new drummer session. The first in a tab is The Original;
 * after that at random — never the one who played last, so opening the view
 * again or shuffling shows somebody new.
 */
export function pickPersona(random: () => number = Math.random): Persona {
  if (lastPicked === undefined) {
    lastPicked = PERSONAS[0].id;
    return PERSONAS[0];
  }
  const pool = PERSONAS.filter((p) => p.id !== lastPicked);
  const persona = pool[Math.min(pool.length - 1, Math.floor(random() * pool.length))];
  lastPicked = persona.id;
  return persona;
}
